apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatgpt-pod
  template:
    metadata:
      labels:
        app: chatgpt-pod
    spec:
      containers:
      - name: mychatgptcont
        image: pranay1993/chatgpt-proj:v1
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: OPENAI_API
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: chatgpt-service
spec:
  type: LoadBalancer
  selector:
    app: chatgpt-pod
  ports:
  - port: 80       #Service IP Port
    targetPort: 80   #Container Port
