apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-deploy
spec:
  replicas: 1  # Reduced from 3
  selector:
    matchLabels:
      app: chatgpt-pod
  template:
    metadata:
      labels:
        app: chatgpt-pod
    spec:
      containers:
      - name: mychatgptcont
        image: gcr.io/PROJECT_ID/chatgpt:v1
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        ports:
        - containerPort: 80
        env:
        - name: OPENAI_API
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: API_KEY